-- Add the remaining 9 course modules
INSERT INTO public.modules (course_id, title, description, order_index, content) 
SELECT 
  c.id,
  module_data.title,
  module_data.description,
  module_data.order_index,
  module_data.content::jsonb
FROM public.courses c,
(VALUES 
  (2, 'Obligasjoner og bærekraftige gjeldsinstrumenter', 'Forstå obligasjonsmarkedet og bærekraftige finansieringsinstrumenter', '{"learning_objectives": ["Forstå obligasjonsmarkedet", "Vurdere bærekraftige gjeldsinstrumenter", "Analysere kredittrisiko"], "sections": [{"title": "Introduksjon til obligasjoner", "type": "content", "content": "Obligasjoner er gjeldspapirer som gir investorer rett til å motta renter og tilbakebetaling av hovedstol.\n\n**Viktige begreper:**\n- Pålydende verdi\n- Kupongrente\n- Løpetid\n- Yield to maturity", "video": "Grunnleggende om obligasjoner (5 min)", "exercise": "Beregn yield på en 5-årig obligasjon med 3% kupong"}]}'),
  (3, 'Investeringsanalyse', 'Metoder for å vurdere lønnsomhet og risiko i investeringsprosjekter', '{"learning_objectives": ["Mestre NPV og IRR", "Forstå sensitivitetsanalyse", "Vurdere investeringsrisiko"], "sections": [{"title": "Netto nåverdi (NPV)", "type": "content", "content": "NPV er differansen mellom nåverdien av fremtidige kontantstrømmer og den initiale investeringen.\n\n**Formel:**\nNPV = Σ(CFt / (1+r)^t) - I0\n\n📌 Hvis NPV > 0, er investeringen lønnsom", "video": "NPV-beregninger i praksis (4 min)", "reflection": "Hvorfor er NPV bedre enn enkel tilbakebetalingstid?"}]}'),
  (4, 'ESG-integrering', 'Hvordan integrere miljø-, sosiale og styringsfaktorer i finansielle beslutninger', '{"learning_objectives": ["Forstå ESG-kriterier", "Integrere ESG i investeringsanalyse", "Vurdere ESG-risiko"], "sections": [{"title": "ESG-rammeverk", "type": "content", "content": "ESG står for Environmental, Social, og Governance - tre sentrale faktorer for bærekraftige investeringer.\n\n**Environmental (Miljø):**\n- Klimarisiko\n- Ressursbruk\n- Forurensning\n\n**Social (Sosialt):**\n- Arbeidsforhold\n- Menneskerettigheter\n- Samfunnsengasjement\n\n**Governance (Styring):**\n- Ledelse\n- Korrupsjonsbekjempelse\n- Aksjonærrettigheter", "video": "ESG i praksis: Casestudier (6 min)", "selftest": true}]}'),
  (5, 'Grønne obligasjoner', 'Forstå markedet for grønne finansieringsinstrumenter', '{"learning_objectives": ["Definere grønne obligasjoner", "Forstå sertifiseringsprosesser", "Vurdere green premium"], "sections": [{"title": "Hva er grønne obligasjoner?", "type": "content", "content": "Grønne obligasjoner er gjeldsinstrumenter der midlene øremerkes miljøprosjekter.\n\n**Green Bond Principles:**\n1. Bruk av midler\n2. Prosess for prosjektevaluering\n3. Forvaltning av midler\n4. Rapportering\n\n📌 Markedet for grønne obligasjoner vokser med over 50% årlig", "video": "Grønne obligasjoner i det norske markedet (5 min)", "download": "Oversikt over grønne obligasjoner i Norge (PDF)"}]}'),
  (6, 'EU-taksonomi', 'Forstå EUs klassifiseringssystem for bærekraftige aktiviteter', '{"learning_objectives": ["Forstå taksonomi-kriteriene", "Klassifisere bærekraftige aktiviteter", "Rapportere i henhold til taksonomi"], "sections": [{"title": "EUs taksonomi for bærekraft", "type": "content", "content": "EU-taksonomien er et klassifiseringssystem som definerer miljømessig bærekraftige økonomiske aktiviteter.\n\n**De seks miljømålene:**\n1. Klimaendringer - reduksjon\n2. Klimaendringer - tilpasning\n3. Bærekraftig bruk av vannressurser\n4. Overgang til sirkulær økonomi\n5. Forebygging av forurensning\n6. Beskyttelse av biologisk mangfold\n\n**DNSH-prinsippet:** Do No Significant Harm", "video": "Navigering i EU-taksonomien (4 min)", "exercise": "Klassifiser ulike forretningsaktiviteter i henhold til taksonomien"}]}'),
  (7, 'Risikoanalyse', 'Identifisere, måle og håndtere finansiell risiko i bærekraftige investeringer', '{"learning_objectives": ["Forstå ulike typer risiko", "Måle og kvantifisere risiko", "Utvikle risikohåndteringsstrategier"], "sections": [{"title": "Typer finansiell risiko", "type": "content", "content": "Risiko i bærekraftige investeringer inkluderer både tradisjonelle og nye risikofaktorer.\n\n**Tradisjonell risiko:**\n- Kredittrisiko\n- Markedsrisiko\n- Operasjonell risiko\n\n**ESG-relatert risiko:**\n- Klimarisiko (fysisk og overgangsrisiko)\n- Omdømmerisiko\n- Regulatorisk risiko\n\n📌 Klimarisiko blir i økende grad sett på som systemisk risiko", "video": "Risikomodellering for klimarisiko (5 min)", "reflection": "Hvordan kan du inkludere klimarisiko i tradisjonelle risikomodeller?"}]}'),
  (8, 'Etiske vurderinger', 'Etiske dilemmaer og prinsipper i bærekraftig finans', '{"learning_objectives": ["Forstå etiske teorier", "Håndtere interessekonflikter", "Vurdere etiske investeringsstrategier"], "sections": [{"title": "Etikk i finansverdenen", "type": "content", "content": "Etiske vurderinger i finans handler om å balansere profitt med samfunnsansvar.\n\n**Sentrale etiske teorier:**\n- Konsekvensetikk (utilitarisme)\n- Pliktetikk (deontologi)\n- Dydsetikk\n\n**Etiske investeringsstrategier:**\n- Negativ screening (ekskludering)\n- Positiv screening (best-in-class)\n- ESG-integrering\n- Impact investing\n\n📌 85% av institusjonelle investorer har inkludert ESG-kriterier i investeringspolicyen", "video": "Etiske dilemmaer i praksis (4 min)", "exercise": "Analyser et etisk dilemma fra finansverdenen"}]}'),
  (9, 'Klimafinans', 'Finansiering av klimatiltak og overgang til lavutslippssamfunnet', '{"learning_objectives": ["Forstå klimafinansieringsmekanismer", "Vurdere klimaprosjekter", "Beregne karbonavtrykk"], "sections": [{"title": "Finansiering av klimatiltak", "type": "content", "content": "Klimafinans omfatter finansielle flyter som støtter reduksjon av klimagassutslipp og tilpasning til klimaendringer.\n\n**Klimafinansieringskilder:**\n- Offentlige midler\n- Private investeringer\n- Blended finance\n- Klimafond\n\n**Måling av klimaeffekt:**\n- Karbonavtrykk (Scope 1, 2, 3)\n- Karbonintensitet\n- Temperaturjustering\n\n📌 Paris-avtalen krever 2,3 billioner USD årlig i klimainvesteringer", "video": "Klimafinans i praksis: Norske eksempler (6 min)", "download": "Mal for beregning av karbonavtrykk (Excel)"}]}'),
  (10, 'Praktisk anvendelse', 'Integrering av læringen gjennom praktiske øvelser og casestudier', '{"learning_objectives": ["Anvende læringen i praksis", "Gjennomføre en komplett bærekraftsanalyse", "Presentere anbefalinger"], "sections": [{"title": "Casestudie: Bærekraftig investeringsanalyse", "type": "content", "content": "I denne modulen skal du gjennomføre en komplett analyse av en bærekraftig investering.\n\n**Oppgavens deler:**\n1. Finansiell analyse (DCF, NPV, IRR)\n2. ESG-risikovurdering\n3. Klimaeffektberegning\n4. Regulatorisk compliance (EU-taksonomi)\n5. Etisk vurdering\n6. Anbefaling og presentasjon\n\n**Leveranse:**\nKomplett investeringsnotat på 10-15 sider", "video": "Gjennomgang av case-oppgaven (8 min)", "exercise": "Gjennomfør bærekraftsanalyse av valgt selskap", "download": "Case-template og vurderingskriterier (PDF)"}]}')
) AS module_data(order_index, title, description, content)
WHERE c.title = 'Bærekraftig Foretaksfinans';