-- Create sub-modules for Regnskap (module order_index 2)
INSERT INTO public.sub_modules (module_id, title, order_index, content) 
VALUES 
  ('415a019e-f884-425c-a44c-6174dad293f9', '2.1 Introduksjon til regnskap', 1, '{"sections": [{"title": "Introduksjon til regnskap", "type": "content", "content": "Regnskap er språket i forretningsverdenen. Det gir oss en strukturert måte å måle, registrere og kommunisere økonomisk informasjon om en virksomhet."}]}'),
  ('415a019e-f884-425c-a44c-6174dad293f9', '2.2 Balanseoppstilling', 2, '{"sections": [{"title": "Balanseoppstilling", "type": "content", "content": "Balanseoppstillingen viser selskapets finansielle stilling på et bestemt tidspunkt - hva selskapet eier (eiendeler) og hva det skylder (gjeld og egenkapital)."}]}'),
  ('415a019e-f884-425c-a44c-6174dad293f9', '2.3 Resultatregnskap', 3, '{"sections": [{"title": "Resultatregnskap", "type": "content", "content": "Resultatregnskapet viser selskapets inntekter og kostnader over en periode, og dermed hvor lønnsomt selskapet har vært."}]}'),
  ('415a019e-f884-425c-a44c-6174dad293f9', '2.4 Kontantstrømoppstilling', 4, '{"sections": [{"title": "Kontantstrømoppstilling", "type": "content", "content": "Kontantstrømoppstillingen viser hvordan kontanter har strømmet inn og ut av selskapet i løpet av en periode."}]}'),
  ('415a019e-f884-425c-a44c-6174dad293f9', '2.5 Nøkkeltall og analyse', 5, '{"sections": [{"title": "Nøkkeltall og analyse", "type": "content", "content": "Finansielle nøkkeltall hjelper oss å forstå og sammenligne selskapers prestasjon og finansielle helse."}]}'),
  ('415a019e-f884-425c-a44c-6174dad293f9', '2.6 Oppgaver', 6, '{"sections": [{"title": "Oppgaver", "type": "content", "content": "Praktiske oppgaver for å teste forståelsen av regnskapsprinsipper."}]}');

-- Create sub-modules for Obligasjoner (module order_index 4)  
INSERT INTO public.sub_modules (module_id, title, order_index, content)
VALUES
  ('d3e2a547-18c3-4fac-89ce-6729c2966bb6', '4.1 Hva er en obligasjon?', 1, '{"sections": [{"title": "Hva er en obligasjon?", "type": "content", "content": "En obligasjon er et verdipapir som dokumenterer at noen har lånt ut penger til en annen part – vanligvis en stat, kommune, bank eller et selskap."}]}'),
  ('d3e2a547-18c3-4fac-89ce-6729c2966bb6', '4.2 Obligasjonsstruktur og nøkkeltall', 2, '{"sections": [{"title": "Obligasjonsstruktur og nøkkeltall", "type": "content", "content": "Når du kjøper en obligasjon, er det noen faste komponenter du må kjenne til som bestemmer hvordan avkastning og risiko ser ut."}]}'),
  ('d3e2a547-18c3-4fac-89ce-6729c2966bb6', '4.3 Pris og avkastning på obligasjoner', 3, '{"sections": [{"title": "Pris og avkastning på obligasjoner", "type": "content", "content": "Obligasjoner utstedes vanligvis til en pålydende verdi, men på annenhåndsmarkedet kan de omsettes til priser over eller under pari."}]}'),
  ('d3e2a547-18c3-4fac-89ce-6729c2966bb6', '4.4 Effektiv rente (YTM)', 4, '{"sections": [{"title": "Effektiv rente (Yield to Maturity – YTM)", "type": "content", "content": "Effektiv rente viser den faktiske, årlige avkastningen du får dersom du kjøper en obligasjon i dag og holder den til forfall."}]}'),
  ('d3e2a547-18c3-4fac-89ce-6729c2966bb6', '4.5 Risikofaktorer ved obligasjoner', 5, '{"sections": [{"title": "Risikofaktorer ved obligasjoner", "type": "content", "content": "Selv om obligasjoner ofte oppfattes som trygge investeringer, innebærer de også risiko med ulike typer risikoprofiler."}]}'),
  ('d3e2a547-18c3-4fac-89ce-6729c2966bb6', '4.6 Kredittrating og markedsaktører', 6, '{"sections": [{"title": "Kredittrating og markedsaktører", "type": "content", "content": "Kredittrating er en vurdering av hvor sannsynlig det er at en låntaker vil tilbakebetale lånet sitt."}]}'),
  ('d3e2a547-18c3-4fac-89ce-6729c2966bb6', '4.7 Grønne obligasjoner og bærekraftige lån', 7, '{"sections": [{"title": "Grønne obligasjoner og bærekraftige lån", "type": "content", "content": "Obligasjonsmarkedet spiller en stadig viktigere rolle i det grønne skiftet gjennom grønne obligasjoner."}]}'),
  ('d3e2a547-18c3-4fac-89ce-6729c2966bb6', '4.8 Durasjon og følsomhet', 8, '{"sections": [{"title": "Durasjon – obligasjonens følsomhet for renteendringer", "type": "content", "content": "Durasjon er et mål på obligasjonens rente-eksponering og hvor mye obligasjonens pris vil endre seg ved renteendringer."}]}');

-- Create sub-modules for Aksjer og aksjeprising (module order_index 5)
INSERT INTO public.sub_modules (module_id, title, order_index, content)
VALUES
  ('07ebd646-afb0-4cc6-9bbc-0c44022461ea', '5.1 Hva er en aksje?', 1, '{"sections": [{"title": "Hva er en aksje – og hvordan fungerer aksjemarkedet?", "type": "content", "content": "En aksje er en eierandel i et aksjeselskap som gir rett til utbytte, stemmerett, kapitalgevinst og restkrav på selskapets verdier."}]}'),
  ('07ebd646-afb0-4cc6-9bbc-0c44022461ea', '5.2 Aksjeprising og verdsettelse', 2, '{"sections": [{"title": "Hva er aksjeprising og hvorfor er det viktig?", "type": "content", "content": "Aksjeprising handler om å estimere den sanne verdien av et selskaps aksjer basert på fremtidige kontantstrømmer og risiko."}]}'),
  ('07ebd646-afb0-4cc6-9bbc-0c44022461ea', '5.3 Fundamental analyse', 3, '{"sections": [{"title": "Fundamental analyse: datainnhenting og regnskapsanalyse", "type": "content", "content": "Fundamental analyse starter med grundig gjennomgang av regnskapstall og justering for engangsposter."}]}'),
  ('07ebd646-afb0-4cc6-9bbc-0c44022461ea', '5.4 Verdsettelsesmodeller DDM og FCFE', 4, '{"sections": [{"title": "Verdsettelsesmodeller: DDM og FCFE", "type": "content", "content": "DDM verdsetter aksjer basert på nåverdien av fremtidige utbytter, mens FCFE representerer kontantstrømmen tilgjengelig for aksjonærene."}]}'),
  ('07ebd646-afb0-4cc6-9bbc-0c44022461ea', '5.5 Multippelanalyse', 5, '{"sections": [{"title": "Verdsettelse med multippelanalyse (P/E, EV/EBITDA, etc.)", "type": "content", "content": "Multipler gir et raskt estimat basert på markedsdata for sammenlignbare selskaper."}]}'),
  ('07ebd646-afb0-4cc6-9bbc-0c44022461ea', '5.6 Praktisk case', 6, '{"sections": [{"title": "Praktisk case: sammenligning av ulike verdsettelsesmetoder", "type": "content", "content": "Gjennomgang av et fiktivt teknologiselskap med beregning via ulike verdsettelsesmetoder."}]}'),
  ('07ebd646-afb0-4cc6-9bbc-0c44022461ea', '5.7 Markedseffisiens', 7, '{"sections": [{"title": "Markedseffisiens og prisdannelse", "type": "content", "content": "Efficient Market Hypothesis og de tre gradene av markedseffisiens."}]}'),
  ('07ebd646-afb0-4cc6-9bbc-0c44022461ea', '5.8 ESG og bærekraft', 8, '{"sections": [{"title": "ESG og bærekraft i aksjeanalyse", "type": "content", "content": "ESG-faktorer påvirker både risiko og avkastning og må integreres i moderne aksjeanalyse."}]}'),
  ('07ebd646-afb0-4cc6-9bbc-0c44022461ea', '5.9 Oppgaver', 9, '{"sections": [{"title": "Oppgaver", "type": "content", "content": "Selvtest og praktiske oppgaver for å teste kunnskap om aksjeanalyse og verdsettelse."}]}');