UPDATE sub_modules 
SET content = jsonb_set(
  content,
  '{sections}',
  '[
    {
      "type": "content",
      "title": "Grunnleggende forholdet mellom risiko og avkastning",
      "content": "Når vi investerer, bytter vi en sikker krone i dag mot usikre kroner i morgen. **Avkastning** er belønningen vi forventer å få for å utsette forbruket – løpende kontantstrømmer pluss prisgevinst. **Risiko** er usikkerheten rundt hvor store disse kronene faktisk blir, vanligvis målt som varians eller standardavvik i avkastningen.\n\n!insight Forholdet mellom risiko og avkastning danner finansfagets grunnfjell: høyere forventet avkastning krever høyere risiko, og omvendt. Dette er ikke en tilfeldighet, men et fundamentalt prinsipp som gjenspeiles i alle finansmarkeder.\n\n!video[Introduksjon til risiko-avkastning sammenhengen](https://www.youtube.com/watch?v=dQw4w9WgXcQ)\n\nKlassiske \"risiko-/avkastning-skyer\" viser nettopp dette bytteforholdet: porteføljer med lav standardavvik ligger nederst til venstre, mens de med høy standardavvik – men også potensial for høy gevinst – ligger øverst til høyre.\n\n!component:risk-return-viz\n\n!think Tenk på dette som en markedsplass: Hvis høy avkastning var tilgjengelig uten høy risiko, ville alle valgt dette. Konkurransen ville presse prisene opp (og avkastningen ned) til balanse ble gjenopprettet.\n\n?? Hvorfor tror du at det ikke finnes \"gratis lunsj\" i finansmarkedene? Hva skjer når alle investorer ønsker samme type investering?"
    },
    {
      "type": "content", 
      "title": "Hvorfor er temaet viktig?",
      "content": "Forståelse av risiko-avkastning forholdet er kritisk for tre hovedområder:\n\n**Kapitalallokering** – Bedrifters investeringsbeslutninger og investorers porteføljevalg bestemmes av hvor mye risiko de må ta for å oppnå ønsket avkastning.\n\n**Kapitalkostnad** – Banker, aksjeanalytikere og ESG-analytikere bruker risikomål (beta, durasjon, likviditetspåslag) for å sette kapitalkrav og rabatter.\n\n**Regulerings- og bærekraftsperspektiv** – EUs taksonomi krever at selskaper vurderer klimarisiko i avkastningsvurderingen; ignorert risiko kan raskt bli virkelig kostnad.\n\n!video[Hvorfor risiko-avkastning er viktig for bedrifter](https://www.youtube.com/watch?v=dQw4w9WgXcQ)\n\n!insight I dagens verden blir risiko-avkastning analyser stadig viktigere. Klimaendringer, geopolitisk uro og teknologiske disruptions skaper nye former for risiko som må prises inn i investeringsbeslutninger.\n\n**Praktiske konsekvenser:**\n- **Personlig økonomi:** Din pensjonssparing, boliglån og forsikringspremier\n- **Bedriftsstrategi:** Hvilke prosjekter som får grønt lys\n- **Samfunnsøkonomi:** Hvordan kapital fordeles i økonomien\n\n?? Tenk på din egen økonomi: Hvor ser du risiko-avkastning avveininger i dagliglivet? For eksempel ved valg av bolig, utdanning eller jobb?\n\n?? Hvorfor tror du at regulatoriske krav som EU-taksonomien blir stadig viktigere for å forstå risiko?"
    },
    {
      "type": "content",
      "title": "Historisk utvikling av risiko-avkastning teori",
      "content": "Forståelsen av risiko og avkastning har utviklet seg dramatisk gjennom historien:\n\n**1930-tallet:** Investorers mavefølelse rådet; risiko ble oppfattet som sjansen for tap mer enn som et eksakt tall.\n\n**1952:** Harry M. Markowitz sin \"Portfolio Selection\" ga oss moderne porteføljeteori: det er kombinasjonen av aktiva – og korrelasjonen dem imellom – som avgjør porteføljerisikoen. \"Ikke legg alle eggene i én kurv\", som Markowitz selv oppsummerte da han tok imot Nobelprisen i 1990.\n\n**1964-1965:** William Sharpe, John Lintner m.fl. koblet risiko direkte til forventet avkastning gjennom Capital Asset Pricing Model (CAPM). Modellen sier at bare den delen av risikoen som ikke kan diversifiseres bort – systematisk risiko, målt ved beta – gir krav på risikopremie.\n\n**1970-2000:** Empiriske datasett som \"Stocks, Bonds, Bills & Inflation\" viste systematiske mønstre: aksjer har høyere gjennomsnittlig avkastning enn obligasjoner, men også større volatilitet.\n\n**2000-tallet til i dag:** Risikobegrepet utvides til å omfatte likviditet, motparts- og klimarisiko. Markedsdata i sanntid, big data-analyse og stresstesting gjør risikostyring mer presis, samtidig som regulatoriske krav (Basel III/IV, EU-taksonomien) gjør konsekvensen av feilprising større.\n\n!video[Fra Markowitz til moderne risikostyring](https://www.youtube.com/watch?v=dQw4w9WgXcQ)\n\n!think Hver av disse utviklingstrinnene kom som respons på finansielle kriser eller markedsendringer. Moderne porteføljeteori etter 1930-tallets børskrakk, CAPM etter 1960-tallets markeds-boom, og dagens fokus på klimarisiko etter økende bevissthet om bærekraft.\n\n**Nobelpriser for risiko-avkastning forskning:**\n- **1990:** Harry Markowitz, William Sharpe, Merton Miller\n- **1997:** Robert Merton, Myron Scholes (opsjoner og derivater)\n- **2013:** Eugene Fama, Lars Peter Hansen, Robert Shiller (markedseffisiens)\n\n?? Hvilken av disse utviklingene tror du har hatt størst praktisk betydning for vanlige investorer? Hvorfor?\n\n?? Hva tror du blir neste store gjennombrudd i risiko-avkastning teorien? Kunstig intelligens? Klimamodellering? Noe annet?"
    },
    {
      "type": "content", 
      "title": "Moderne utfordringer og trender",
      "content": "Dagens finansmarkeder står overfor nye former for risiko som tradisjonelle modeller ikke fullt ut fanger opp:\n\n**Klimarisiko** – Fysiske klimaendringer og regulatoriske tiltak skaper nye former for systematisk risiko som påvirker hele økonomien.\n\n**Teknologisk disrupsjon** – Kunstig intelligens, blockchain og andre teknologier endrer hele bransjer på kort tid.\n\n**Geopolitisk risiko** – Handelskriger, sanksjoner og politisk ustabilitet skaper nye korrelasjoner mellom markeder.\n\n**Likviditetsrisiko** – Algoritmisk handel og passive investeringer kan forsterke markedsvolatilitet.\n\n!insight Tradisjonelle risiko-avkastning modeller bygger på historiske data, men i en verden med raske endringer kan \"dette har aldri skjedd før\" være realiteten vi må forholde oss til.\n\n!video[Nye risikoer i moderne finansmarkeder](https://www.youtube.com/watch?v=dQw4w9WgXcQ)\n\n**ESG og bærekraftig finans:**\nInvestorer krever stadig mer informasjon om:\n- **Environmental:** Klimafotavtrykk, resssursbruk\n- **Social:** Arbeidsforhold, samfunnsansvar  \n- **Governance:** Selskapsstyring, etikk\n\n!think ESG-faktorer kan både redusere risiko (bedre styring) og skape ny risiko (regulatoriske endringer). De fleste studier viser at god ESG-praksis korrelerer med bedre langsiktig avkastning.\n\n?? Hvordan tror du klimaendringer vil påvirke risiko-avkastning profilene til ulike bransjer i årene fremover?\n\n?? Hvis du skulle investere for de neste 20 årene, hvilke nye risikoer ville du vært mest bekymret for?"
    },
    {
      "type": "content",
      "title": "Kapitlets oppbygging og læringsmål",
      "content": "Gjennom dette kapitlet vil du lære å navigere i risiko-avkastning landskapet gjennom både teori og praktiske verktøy:\n\n**Begrepsgrunnlag:**\n• Definisjoner av avkastning, varians og standardavvik\n• Historiske vs. fremtidige risikomål\n\n**Historiske tall:**\n• Hvordan ulike aktivaklasser har belønnet risiko over tid\n• Sammenligning av aksjer, obligasjoner og alternative investeringer\n\n**Diversifisering:**\n• Hvorfor korrelasjon er nøkkelen til risikoreduksjon\n• Praktiske porteføljeeksempler\n\n**Systematisk vs. usystematisk risiko:**\n• Innføring i beta og CAPM\n• Hvilken risiko kan diversifiseres bort\n\n**Risikojusterte prestasjonsmål:**\n• Sharpe- og Treynor-rater\n• Jensens alpha og informasjonsrater\n\n**Bærekraftsdimensjonen:**\n• Klimarisiko og ESG-premier\n• Regulatoriske rammeverk\n\n!insight Målet er ikke å eliminere all risiko – det er umulig og uønsket. Målet er å forstå hvilken risiko du tar, få betalt for den, og optimalisere forholdet mellom risiko og avkastning.\n\n**Praktiske verktøy du vil mestre:**\n- Beregne historisk avkastning og volatilitet\n- Bygge effisiente porteføljer\n- Estimere betaverdier og risikopremier\n- Analysere risikojustert prestasjon\n- Integrere ESG-faktorer i investeringsanalyse\n\n!video[Oversikt over verktøy og teknikker](https://www.youtube.com/watch?v=dQw4w9WgXcQ)\n\n**Hvorfor dette er viktig for din karriere:**\nUansett om du skal jobbe i bank, forsikring, pensjonsfond, bedrifter eller starte egen virksomhet – forståelse av risiko-avkastning sammenhenger er grunnleggende for å ta gode finansielle beslutninger.\n\n?? Hvilken del av dette kapitlet ser du mest frem til å lære om? Hvorfor?\n\n?? Hvordan tror du denne kunnskapen vil være nyttig i din fremtidige karriere eller private økonomi?\n\n?? Basert på det du har lært så langt, hvordan ville du forklart risiko-avkastning sammenhengen til en venn som ikke har finansbakgrunn?"
    }
  ]'
)
WHERE id = (
  SELECT sm.id 
  FROM sub_modules sm 
  JOIN modules m ON sm.module_id = m.id 
  WHERE m.order_index = 6 AND sm.order_index = 1
);